config/routes.rb
Rails.application.routes.draw do
  # Rotas do Devise para autenticação
  devise_for :users

  # Rotas para fichas cadastrais (somente catequistas podem gerenciar)
  resources :ficha_cadastrals, only: [:index, :new, :create, :edit, :update, :destroy]

  # Definir a rota raiz (página inicial) do aplicativo
  root 'pages#home'

  # Rotas para Aulas
  resources :aulas

  # Rotas para Postagens e Comentários
  resources :postagems do
    resources :mensagens, only: [:create, :destroy]
    resources :comentarios, only: [:create, :edit, :update, :destroy]
  end

  # Rotas para Notificações
  resources :notifications, only: [:index] do
    member do
      patch :mark_as_read
    end
  end

  # Rotas para Orações
  resources :oracoes

  # Rota para o Dashboard do Catequizando
  get 'catequizando/dashboard', to: 'catequizando#dashboard', as: 'catequizando_dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/aula.rb
class Aula < ApplicationRecord
  belongs_to :user
  has_rich_text :detailed_content
  has_one_attached :image

  validates :title, presence: { message: " - O título da aula é obrigatório." }
  validates :content, presence: { message: "- A descrição da aula é obrigatória." }
  validates :detailed_content, presence: { message: "- O conteúdo detalhado da aula é obrigatório." }
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :postagem
  belongs_to :user

   # Validação para garantir que o conteúdo não seja vazio
   validates :content, presence: { message: "O comentário não pode estar vazio." }
end

app/models/ficha_cadastral.rb
class FichaCadastral < ApplicationRecord
  belongs_to :user
  belongs_to :catequizando, class_name: 'User', foreign_key: 'user_id'
  belongs_to :catequista, class_name: 'User', foreign_key: 'catequista_id'




  validates :nome, :endereco, :data_nascimento, :telefone, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/mensagem.rb
class Mensagem < ApplicationRecord
  belongs_to :user
  belongs_to :receiver, class_name: 'User'
  belongs_to :postagem  # Uma mensagem pertence a uma postagem
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notifiable, polymorphic: true

  scope :unread, -> { where(read: false) }

  def message
    case notifiable
    when Comentario
      case self.message_type
      when 'created'
        "Novo comentário na postagem: '#{notifiable.postagem.title}'"
      when 'updated'
        "Comentário alterado na postagem: '#{notifiable.postagem.title}'"
      when 'deleted'
        "Comentário removido da postagem: '#{notifiable.postagem.title}'"
      end
    when Postagem
      case self.message_type
      when 'created'
        "Nova postagem: '#{notifiable.title}'"
      when 'updated'
        "Postagem alterada: '#{notifiable.title}'"
      when 'deleted'
        "Postagem removida: '#{notifiable.title}'"
      end
    else
      "Nova notificação"
    end
  end
end

app/models/oracao.rb
class Oracao < ApplicationRecord
  belongs_to :user

end

app/models/postagem.rb
class Postagem < ApplicationRecord
  belongs_to :user
  has_many :mensagens, class_name: "Mensagem", dependent: :destroy
  has_many :comentarios, dependent: :destroy

  validates :title, presence: { message: " - O título da postagem é obrigatório." }
  validates :content, presence: { message: "- O conteúdo da postagem é obrigatório." }
end

app/models/user.rb
class User < ApplicationRecord
  # Inclui os módulos do Devise
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Define enum para o papel do usuário
  enum role: { catequista: 'catequista', catequisando: 'catequisando' }

  # Associações
  has_many :mensagens
  has_many :postagems
  has_many :aulas
  has_many :comentarios
  has_many :notifications, dependent: :destroy
  has_one :ficha_cadastral, dependent: :destroy
  has_many :fichas_cadastrais, foreign_key: 'catequista_id', class_name: 'FichaCadastral'
  has_one :ficha_cadastral, foreign_key: 'user_id'
  # Validações
  validates :role, presence: true, inclusion: { in: roles.keys }

  # Definir papel padrão
  before_create :set_default_role

  # Métodos de verificação de permissões
  def catequista?
    role == 'catequista'
  end

  def catequisando?
    role == 'catequisando'
  end

  private

  def set_default_role
    self.role ||= 'catequisando'
  end
end

app/controllers/aulas_controller.rb
class AulasController < ApplicationController
  before_action :set_aula, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :authorize_catequista!, except: [:index, :show]
  # GET /aulas or /aulas.json
  def index
    @aulas = Aula.order(:created_at)
  end

  # GET /aulas/1 or /aulas/1.json
  def show
  end

  # GET /aulas/new
  def new
    @aula = Aula.new
  end

  # GET /aulas/1/edit
  def edit
  end

    def create
      @aula = Aula.new(aula_params)
      @aula.user = current_user
  
      if @aula.save
        Notification.create(user: current_user, notifiable: @aula, message: "Aula criada: #{@aula.title}")
        redirect_to @aula, notice: 'Aula criada com sucesso.'
      else
        render :new
      end
    end
  
    def update
      @aula = Aula.find(params[:id])
      if @aula.update(aula_params)
        Notification.create(user: current_user, notifiable: @aula, message: "Aula alterada: #{@aula.title}")
        redirect_to @aula, notice: 'Aula alterada com sucesso.'
      else
        render :edit
      end
    end
  
    def destroy
      @aula = Aula.find(params[:id])
      @aula.destroy
      Notification.create(user: current_user, notifiable: @aula, message: "Aula removida: #{@aula.title}")
      redirect_to aulas_url, notice: 'Aula removida com sucesso.'
    end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aula
      @aula = Aula.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aula_params
      params.require(:aula).permit(:title, :content, :detailed_content, :image)
    end

    def authorize_catequista!
      unless current_user.catequista?
        redirect_to root_path, alert: 'Acesso negado. Apenas catequistas podem acessar esta página.'
      end
    end


end

app/controllers/oracoes_controller.rb
class OracoesController < ApplicationController
  before_action :set_oracao, only: %i[show edit update destroy]
  before_action :authenticate_user! # Garante que o usuário esteja logado para criar, editar ou excluir

  def index
    @oracoes = Oracao.order(created_at: :desc) #  para mostrar apenas as orações do usuário logado: Oracao.where(user: current_user)
  end

  def show
  end

  def new
    @oracao = Oracao.new
  end

  def create
    @oracao = Oracao.new(oracao_params)
    @oracao.user = current_user # Associa a oração ao usuário logado
    if @oracao.save
      redirect_to @oracao, notice: 'Oração criada com sucesso.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @oracao.update(oracao_params)
      redirect_to @oracao, notice: 'Oração atualizada com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @oracao.destroy
    redirect_to oracoes_url, notice: 'Oração removida com sucesso.'
  end

  private

  def set_oracao
    @oracao = Oracao.find(params[:id])
  end

  def oracao_params
    params.require(:oracao).permit(:titulo, :conteudo)
  end
end

app/controllers/pages_controller.rb
# app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # Buscar as notificações do usuário logado, caso exista
    if user_signed_in?
      @notifications = current_user.notifications.order(created_at: :desc).limit(7)
      @total_postagens = current_user.postagems.count
      @total_comentarios = current_user.comentarios.count
      @total_aulas = Aula.count
    else
      @notifications = []
   
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aulas_helper.rb
module AulasHelper
end

app/helpers/catequizando_helper.rb
module CatequizandoHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/mensagems_helper.rb
module MensagemsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/oracoes_helper.rb
module OracoesHelper
end

app/helpers/postagems_helper.rb
module PostagemsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/shared/_banner.html.erb
<!-- app/views/shared/_banner.html.erb -->

<!-- Coluna para o banner à direita -->
<div class="col-md-2">
  <!-- Div para exibir a data e hora do encontro -->
  <div class="date-time-container">
    <h3>Acesso</h3>
    <p><%= Time.now.strftime("%d/%m/%Y - %H:%M") %></p> <!-- Exibe a data e a hora atuais -->
  </div>

  <!-- Banner abaixo da data e hora -->
  <div class="banner">
    <div class="banner-content">
      <h2>Bem-vindo!</h2>
      <p>Este espaço é utilizado para suas aulas e tarefas!</p>
 
      <br>
      <%= image_tag "imag3.jpg", alt: "Imagem do Banner", class: "img-fluid" %>
     <br>
     <br>
    <!-- Exibe o nome do usuário logado -->
      <% if user_signed_in? %>
        <p><strong>Usuário:</strong> <%= current_user.email %></p>
      <% else %>
        <p><strong>Usuário:</strong> Convidado</p>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_banner_postagem.html.erb
<!-- app/views/shared/_banner.html.erb -->


    <div class="col-md-2">

      <div class="date-time-container">
        <h3>Acesso</h3>
        
        <p><%= Time.now.strftime("%d/%m/%Y - %H:%M") %></p> 
      </div>

      <div class="banner">
        <div class="banner-content">
          <h2>Bem-vindo!</h2>
          <p>
          <p>Este espaço é utilizado para suas aulas e tarefas!</p>
          <br>
          <%= image_tag "imag3.jpg", alt: "Imagem do Banner", class: "img-fluid" %>
           <br>
           <br>
    <!-- Exibe o nome do usuário logado -->
      <% if user_signed_in? %>
        <p><strong>Usuário:</strong> <%= current_user.email %></p>
      <% else %>
        <p><strong>Usuário:</strong> Convidado</p>
      <% end %>
        </div>
      </div>
    </div>

app/views/shared/_notification_count.html.erb
<!-- app/views/shared/_notification_count.html.erb -->
<div class="mt-3">
  <%= link_to "Notificações (#{unread_notifications})", notifications_path, class: 'btn btn-info' %>
</div>

app/views/shared/_sidebar.html.erb
<!-- app/views/shared/_sidebar.html.erb -->
<div class="col-md-2 sidebar">
  <div class="logo mb-4 text-center">
    <%= image_tag "info2.png", alt: "Logotipo", class: "img-fluid logo-small" %>
  </div>

  <ul class="nav flex-column">
    <li class="nav-item">
      <%= link_to 'Página Inicial', root_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Aulas', aulas_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Postagens', postagems_path, class: 'nav-link' %>
    </li>

    <!-- Link para o Dashboard do Catequizando, visível apenas para catequizandos -->
    <% if current_user.catequisando? %>
      <li class="nav-item">
        <%= link_to 'Meus dados', catequizando_dashboard_path, class: 'nav-link' %>
      </li>
    <% end %>

    <!-- Link para Gerenciar Fichas Cadastrais, visível apenas para Catequistas -->
    <% if current_user.catequista? %>
      <li class="nav-item">
        <%= link_to 'Gerenciar Fichas Cadastrais', ficha_cadastrals_path, class: 'nav-link' %>
      </li>
    <% end %>
  </ul>

  <div class="position-absolute text-center" style="bottom: 20px; width: 90%;">
    <% if user_signed_in? %>
      <%= button_to "Sair", destroy_user_session_path, method: :delete, class: "btn btn-danger", style: "width: 80%;" %>
    <% else %>
      <%= link_to "Entrar", new_user_session_path, class: "btn btn-primary", style: "width: 80%;" %>
    <% end %>
  </div>
</div>