config/routes.rb
Rails.application.routes.draw do
  # Rotas do Devise para autenticação
  devise_for :users

  # Rotas para fichas cadastrais (somente catequistas podem gerenciar)
  resources :ficha_cadastrals, only: [:index, :new, :create, :edit, :update, :destroy]

  # Definir a rota raiz (página inicial) do aplicativo
  root 'pages#home'

  # Rotas para Aulas
  resources :aulas

  # Rotas para Postagens e Comentários
  resources :postagems do
    resources :mensagens, only: [:create, :destroy]
    resources :comentarios, only: [:create, :edit, :update, :destroy]
  end

  # Rotas para Notificações
  resources :notifications, only: [:index] do
    member do
      patch :mark_as_read
    end
  end

  # Rotas para Orações
  resources :oracoes

  # Rota para o Dashboard do Catequizando
  get 'catequizando/dashboard', to: 'catequizando#dashboard', as: 'catequizando_dashboard'
end

app/models/postagem.rb
class Postagem < ApplicationRecord
  belongs_to :user
  has_many :mensagens, class_name: "Mensagem", dependent: :destroy
  has_many :comentarios, dependent: :destroy

  validates :title, presence: { message: " - O título da postagem é obrigatório." }
  validates :content, presence: { message: "- O conteúdo da postagem é obrigatório." }
end

app/controllers/postagems_controller.rb
class PostagemsController < ApplicationController
  before_action :set_postagem, only: [:show, :edit, :update, :destroy]
  before_action :authorize_catequista!, only: [:new, :create, :edit, :update, :destroy]
  # GET /postagems or /postagems.json
  def index
    # @postagens = Postagem.includes(:comentarios).all
    @postagens = Postagem.order(:created_at) 

    
  end

  # GET /postagems/1 or /postagems/1.json
  def show
    @postagem = Postagem.find(params[:id])
  end

  # GET /postagems/new
  def new
    @postagem = Postagem.new
  end

  # GET /postagems/1/edit
  def edit
  end

  def create
    @postagem = Postagem.new(postagem_params)
    @postagem.user = current_user
  
    if @postagem.save
      Notification.create(user: current_user, notifiable: @postagem, message_type: 'created')
      redirect_to @postagem, notice: 'Postagem criada com sucesso.'
    else
      render :new
    end
  end
  
  def update
    @postagem = Postagem.find(params[:id])
    
    if @postagem.update(postagem_params)
      Notification.create(user: current_user, notifiable: @postagem, message_type: 'updated')
      redirect_to @postagem, notice: 'Postagem atualizada com sucesso.'
    else
      render :edit
    end
  end
  
  def destroy
    @postagem = Postagem.find(params[:id])
    @postagem.destroy
    Notification.create(user: current_user, notifiable: @postagem, message_type: 'deleted')
    redirect_to postagems_path, notice: 'Postagem excluída com sucesso.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_postagem
      @postagem = Postagem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def postagem_params
      params.require(:postagem).permit(:title, :content, :user_id)
    end

    def authorize_catequista!
      unless current_user.catequista?
        redirect_to postagems_path, alert: 'Acesso negado. Apenas catequistas podem gerenciar postagens.'
      end
    end
end

app/helpers/postagems_helper.rb
module PostagemsHelper
end

app/views/postagems/_form.html.erb
<div class="container mt-5">
  <%= form_with(model: postagem, local: true) do |form| %>

    <!-- Exibição de erros -->
    <% if postagem.errors.any? %>
      <div class="alert alert-danger">
        <h4><%= pluralize(postagem.errors.count, "erro") %> impediu que a postagem fosse salva:</h4>
        <ul>
          <% postagem.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <!-- Campo para o título da postagem -->
    <div class="mb-3">
      <%= form.label :title, "Título da Postagem", class: "form-label fw-bold" %>
      <%= form.text_field :title, class: "form-control form-control-underline", placeholder: "Digite o título da postagem" %>
    </div>

    <!-- Campo para o conteúdo da postagem -->
    <div class="mb-3">
      <%= form.label :content, "Conteúdo da Postagem", class: "form-label fw-bold" %>
      <%= form.rich_text_area :content, class: "form-control form-control-underline w-100", placeholder: "Escreva o conteúdo da postagem", style: "height: 450px; overflow-y: auto;" %>

    
    </div>
    
  
  <div class="mb-3">
     <!-- Campo oculto para o ID do usuário (caso o usuário seja definido automaticamente) -->
    <%= form.hidden_field :user_id, value: current_user.id %>
</div>



    <!-- Botão de submissão -->
    <div>
      <%= form.submit "Salvar Postagem", class: "btn btn-primary btn shadow-sm" %>
    </div>

  <% end %>
</div>

app/views/postagems/_postagem.html.erb
<div id="<%= dom_id postagem %>">
  <p>
    <strong>Title:</strong>
    <%= postagem.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= postagem.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= postagem.user_id %>
  </p>

</div>

app/views/postagems/edit.html.erb
<!-- Sidebar -->
<div class="col-md-2 d-none d-md-block">
  <%= render 'shared/sidebar' %>
</div>

<div class="container mt-5">
  <% content_for :title, "Editing postagem" %>
    <h1>Editando a postagem</h1>
    <%= render "form", postagem: @postagem %>
    <br>
  <div>
    <%= link_to "Mostrar esta postagem", @postagem %> |
    <%= link_to "Voltar para postagens", postagems_path %>
  </div>
 </div>  

app/views/postagems/index.html.erb
<div class="container-fluid mt-5">
  <div class="row">
    <!-- Sidebar -->
    <div class="col-md-2 d-none d-md-block">
      <%= render 'shared/sidebar' %>
    </div>

    <!-- Conteúdo principal -->
    <div class="col-md-8 offset-md-0">
      <header class="page-header">
        <h1 class="page-title">Postagens</h1>
      </header>

       <% if current_user.catequista? %> 
        <div class="mb-3 text-center">
          <%= link_to new_postagem_path, class: 'btn btn-success' do %>
            <i class="fas fa-plus"></i> Nova Postagem
          <% end %>
        </div>
       <% end %>  

      <div class="row card-container">
        <% @postagens.each do |postagem| %>
          <div class="col-md-12 mb-4"> <!-- Agora cada card ocupa a largura total -->
            <div class="card h-100">
              <div class="card-body position-relative">
                
                <!-- Ícones de edição e exclusão na parte superior direita -->
                <% if postagem.user == current_user %>
                  <div class="position-absolute" style="top: 10px; right: 10px;">
                    <%= link_to edit_postagem_path(postagem), class: 'text-primary me-2' do %>
                      <i class="fas fa-edit"></i>
                    <% end %>

                    <%= button_to postagem_path(postagem), method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' }, class: 'btn btn-link text-text-primary p-0', form: { class: 'd-inline' } do %>
                      <i class="fas fa-trash-alt"></i>
                    <% end %>
                  </div>
                <% end %>

                <h5 class="card-title"><%= postagem.title %></h5>
                <p class="card-text"><%= sanitize(postagem.content).truncate(150) %></p>
                <p class="text-muted">
                  Postado por <%= postagem.user.email %> em <%= postagem.created_at.strftime("%d/%m/%Y") %>
                </p>
                <%= link_to 'Ver Postagem', postagem_path(postagem), class: 'btn btn-primary' %>
              </div>

              <!-- Seção de Comentários com scroll -->
              <div class="comments mt-3" style="max-height: 200px; overflow-y: auto;">
                <% if postagem.comentarios.any? %>
                  <% postagem.comentarios.each do |comentario| %>
                    <div class="mb-4 p-3 border rounded bg-light">
                      <strong class="text-primary"><%= comentario.user.email %>:</strong>
                      <p class="mt-2"><%= comentario.content %></p>

                      <div class="d-flex justify-content-between align-items-center mt-2">
                        <!-- Exibir data de criação e atualização -->
                        <p class="text-muted mb-0" style="font-size: 13px;">
                          Comentário postado em <%= comentario.created_at.strftime("%d/%m/%Y às %H:%M") %>
                          <% if comentario.created_at != comentario.updated_at %>
                            | Comentário alterado em <%= comentario.updated_at.strftime("%d/%m/%Y às %H:%M") %>
                          <% end %>
                        </p>

                        <!-- Links de edição e exclusão para o autor do comentário -->
                        <% if comentario.user == current_user %>
                          <div>
                            <%= link_to edit_postagem_comentario_path(postagem, comentario), class: 'text-warning me-2' do %>
                              <i class="fas fa-edit"></i>
                            <% end %>

                            <%= button_to postagem_comentario_path(postagem, comentario), method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' }, class: 'btn btn-link text-danger p-0', form: { class: 'd-inline' } do %>
                              <i class="fas fa-trash-alt"></i>
                            <% end %>
                          </div>
                        <% end %>
                      </div>
                    </div>
                  <% end %>
                <% else %>
                  <p class="text-muted text-center mb-4">Ainda não há comentários nesta postagem.</p>
                <% end %>
              </div>

            </div>
          </div>
        <% end %>
      </div>
    </div>

    <!-- Banner Postagem -->
    <%= render 'shared/banner_postagem' %>
  </div>
</div>

app/views/postagems/new.html.erb
<!-- Sidebar -->
<div class="col-md-2 d-none d-md-block">
  <%= render 'shared/sidebar' %>
</div>

<div class="container mt-5">
<% content_for :title, "New postagem" %>
<h1>Nova Postagem</h1>
<hr>
<%= render "form", postagem: @postagem %>
<br>
<div>
        <%= link_to "Voltar para Postagens", postagems_path, style: "color: #343a40;" %>
</div>
</div>

app/views/postagems/show.html.erb
<div class="container mt-5">

    <%= render 'shared/sidebar' %>

  <!-- Título da Postagem -->
  <h1 class="mb-3"><%= @postagem.title %></h1>
  <p class="text-muted">
    Postado por <strong><%= @postagem.user.email %></strong> em <%= @postagem.created_at.strftime("%d/%m/%Y") %>
  </p>
  <hr>

  <!-- Conteúdo da Postagem -->
  <div class="content mb-4">
    <p><%= simple_format(@postagem.content) %></p>
  </div>

  <!-- Seção de Comentários -->
  <h3 class="mt-5">Comentários</h3>
  <hr>

  <div class="comments">
    <% if @postagem.comentarios.any? %>
      <% @postagem.comentarios.each do |comentario| %>
        <div class="mb-4 p-3 border rounded bg-light">
          <strong class="text-primary"><%= comentario.user.email %>:</strong>
          <p class="mt-2"><%= comentario.content %></p>
        </div>
      <% end %>
    <% else %>
      <p class="text-muted">Ainda não há comentários nesta postagem.</p>
    <% end %>
  </div>

  <!-- Formulário para Adicionar Comentário -->
  <% if user_signed_in? %>
    <div class="add-comment mt-5">
      <h4>Adicionar Comentário</h4>
      <%= form_with(model: [@postagem, Comentario.new], local: true) do |form| %>
        <div class="form-group">
          <%= form.label :content, "Comentar" %>
          <%= form.text_area :content, class: "form-control", rows: 3 %>
        </div>
        <div class="form-group">
          <br>
           <%= form.submit "Enviar", class: "btn btn-primary " %>
           <%= link_to 'Voltar para Postagens', postagems_path, class: 'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>